In [ ]:
import numpy as np
np.set_printoptions(precision = 4,suppress=True)

In [ ]:
a= np.array([[1,2,3,4], [1,1,2,3], [0,1,1,0]])
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


In [ ]:
u, s, vh = np.linalg.svd(a, full_matrices=True)
print(u)
print(u.dot(u.T)) #to check whether u is orthogonal or not
print(vh)

[[ 0.8109  0.0934 -0.5776]
 [ 0.57   -0.3493  0.7437]
 [ 0.1323  0.9324  0.3365]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
[[ 0.2046  0.3443  0.5488  0.7338]
 [-0.2181  0.6561  0.438  -0.5746]
 [ 0.7598 -0.3431  0.4167 -0.3625]
 [-0.5774 -0.5774  0.5774  0.    ]]


In [ ]:
print(s) #it contains the singular values of matrix A

[6.7509 1.1734 0.2186]


In [ ]:
sd= np.diag(s) #makes a 3X3 diagonal matrix with s(singular values) along the diagonal
print(sd)

[[6.7509 0.     0.    ]
 [0.     1.1734 0.    ]
 [0.     0.     0.2186]]


As starting matrix was 3X4(mxn) , so matrix sigma(sd) should also be mxn, but it should contain 3 singular values along the diagonal. so last column will be zero

In [ ]:
b = np.zeros((3,4)) #making b matrix with initially putting all zeros

In [ ]:
b[:,:-1]=sd # it will replace ist 3 columns of b with sd
sigma=b
print(sigma)

[[6.7509 0.     0.     0.    ]
 [0.     1.1734 0.     0.    ]
 [0.     0.     0.2186 0.    ]]


In [ ]:
print(np.dot(np.dot(u,sigma), vh)) #reconstructing matrix a

[[1. 2. 3. 4.]
 [1. 1. 2. 3.]
 [0. 1. 1. 0.]]


For rank 2 approximation of A, we have to make 3rd singular value as zero. 2 rank approximation ------

In [ ]:
s = [6.7509, 1.1734, 0]

Now repeat same steps


In [ ]:
sd= np.diag(s)
print(sd)

[[6.7509 0.     0.    ]
 [0.     1.1734 0.    ]
 [0.     0.     0.    ]]


In [ ]:
b = np.zeros((3,4))
b[:,:-1]=sd
sigma=b
print(sigma) #contains only 2 non-zero singular values

[[6.7509 0.     0.     0.    ]
 [0.     1.1734 0.     0.    ]
 [0.     0.     0.     0.    ]]


In [ ]:
print(np.dot(np.dot(u,sigma), vh)) # this resultant maatrix will have rank 2

[[ 1.0959  1.9567  3.0526  3.9542]
 [ 0.8764  1.0558  1.9322  3.0589]
 [-0.0559  1.0252  0.9693  0.0267]]


In [ ]:
print(a) #compare it with rank 2 approximation.... Nearly same values

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]
